### PR TITLE
Adding 'system_snmp_user' to the special attributes list

### PR DESCRIPTION
**Pull request by tohillm**

### CODE REVIEW

**Comment by mamunozgonzalez** [comment]
Hi @tohillm ,
 thanks, that was quick!! I took the liberty to modify the PR to remove the non needed enumerated values.
I guess I should add some proper instructions to handle this (since this was mainly internal I didn't take the proper time to prepare decent documentation)

Summarizing, the file just contains a list of attributes that must be considered as 'lists' but there is no need to include the enumerations. What you see in https://github.com/fortinet-solutions-cse/ansible_generator/blob/f52ead9a3ece7222c2df078fd96a7ecdedf019aa/special_attributes.lst#L5 is just another attribute which is in a secondary level and thus we have to add the full path to get to it.

**Comment by mamunozgonzalez** [comment]
Merged. Give me some time and I'll regenerate the modules in https://github.com/fortinet-solutions-cse/ansible_fgt_modules

**Comment by mamunozgonzalez** [comment]
Done. Please check https://github.com/fortinet-solutions-cse/ansible_fgt_modules/blob/master/v6.0.2/system_snmp/fortios_system_snmp_user.py

**Comment by tohillm** [comment]
Thanks Miguel. Working!
Mark

**Pull request merged**
