### PR TITLE
Fix issue #26 of ansible_fgt_modules

### PR DESCRIPTION
**Pull request by chillancezen**
for modules added in 2.8,  if no state is provided, let the branch control go to the third clause.

```
if 'state' in data and data['state']: 
     state = data['state'] 
 elif 'state' in data['system_interface'] and data['system_interface']['state']: 
     state = data['system_interface']['state'] 
 else: 
     state = True 
```

the issue context: https://github.com/fortinet-solutions-cse/ansible_fgt_modules/issues/26

### CODE REVIEW

**Comment by sbraz** [comment]
Thanks for the fix. However, what's the point of leaving the `else` clause with `state = True`? I don't see a place where the state is compared to a boolean.

**Comment by chillancezen** [comment]
> Thanks for the fix. However, what's the point of leaving the `else` clause with `state = True`? I don't see a place where the state is compared to a boolean.

when you delete the clause `state = true`, you will get error:
`UnboundLocalError: local variable 'state' referenced before assignment`
this is pure runtime syntax error. 

maybe I will add the code to handle the exceptional cases for `state`.but first I want to make it clear why Miguel leaves `state` as non-required in Ansible 2.8,   @mamunozgonzalez did you have any consideration here ?


thanks,
Link.

**Comment by sbraz** [comment]
With the `state = True` clause, there is another failure because no API request is performed either and this function returns `None`:
https://github.com/fortinet-solutions-cse/ansible_generator/blob/2384a595be17463a0c35da24b920603a72808d24/ansible_templates/code.j2#L89

IMO `state` should now be required but let's wait for Miguel's answer.

**Comment by mamunozgonzalez** [comment]
Hi,
 good spot @sbraz and nice fix @chillancezen. 
'state' was mandatory at the very beginning but then Ansible requested us to move it to a different, inner, scope (one level deeper, below 'system_interface'). The problem is that doing this we couldn't set it as mandatory cause then it would fail for legacy playbooks. So now, we might find 'state' in upper or inner level (above or below 'system_interface' declaration).
Therefore, the only way to go forward was to leave it as 'non mandatory' despite it is theoretically a required parameter.

The final clause "state = True" was just a way to ensure that the variable had a value in case the user forgets to set it (since now it is not mandatory due to the problem stated above). By default it was assumed that the user wants to set/create if nothing is specified.

**Pull request merged**
